version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'monday'
          time: '01:00'
          timezone: 'Asia/Shanghai'
      open-pull-requests-limit: 999
